apiVersion: v1
kind: ReplicationController
metadata:
  name: learning-rc
spec:
  replicas: 10
  selector:
    app : hello-world
  template :
    metadata:
      labels:
        app: hello-world
    spec :
      containers:
      - name: hello-world
        image: luckyganesh/learning
        ports:
        - containerPort: 8000